server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**

        - id: requester-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/requesters/**
          filters:
            - AuthenticationFilter

        - id: volunteer-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/volunteers/**
          filters:
            - AuthenticationFilter

        - id: mission-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/missions/**
          filters:
            - AuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.volunteer.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always