name: Auth Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'volunteer-auth-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Pin to a specific version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: |
          cd volunteer-auth-service
          mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: auth-service
          path: volunteer-auth-service/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: 'Production'
      # Removed the URL reference because azure/webapps-deploy@v2 doesn't provide it

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: auth-service

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
