name: Mission Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'mission-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: |
          cd mission-service
          mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: mission-service
          path: mission-service/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mission-service

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: volunteer-mission-service
          publish-profile: ${{ secrets.MISSION_PUBLISH_PROFILE }}
          package: '*.jar'
